version: '3.9'
services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: mohammad
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - '3307:3306'
    volumes:
      - mysql:/var/lib/mysql


volumes:
  mysql: